### ISSUE TITLE
Run server with txadmin

### ISSUE THREAD

**Issue by Harakiric** [ich777/docker-fivem-server#2]
How would i go about if i want to start this container with txadmin enabled?

**Comment by ich777** [comment]
Yes that is possible, according to this page txAdmin is integrated in every FXServer above 2524 and you only have to add '+set txAdminPort 40121' to the start command.

To do that go in your template enter '+set txAdminPort 40121' (without quotes and the port that you preferr - in this case 40121) at 'Start Variables', then you have to also click on 'Add another Path, Port, Variable, Label or Device' and select 'Port' for the Host and Containerport set the above set Port (in this case 40121), click on 'Add' and then on 'Apply'.

After the Container is fully startup you should be able to connect to txAdmin with YOURSERVERIP:YOURSETPORT

Also Please don't double post in the Unraid Forums and here on Github because I simply can't answer when I'm sleeping.
