### ISSUE TITLE
Editing Server.cfg

### ISSUE THREAD

**Issue by MainServerSpace** [ich777/docker-fivem-server#4]
How can I go about updating server.cfg to add my custom loading screen and to update "You don't have sv_projectName/sv_projectDesc set."

**Comment by MainServerSpace** [comment]
Tried inside docker image and it don't have vim or nano? If I edit the files. The docker image filesystem doesn't stay persistent  across.

**Comment by ich777** [comment]
Do you use this container on unRAID or do you use it from the CLI, have you mounted the volumes correctly?
Just edit the server.cfg file with any editor you want on the host.

You also have the ability to install vi or nano in the container by typing in `apt update` & `apt install nano` for example, if you do it like that I would also recommend to type in `su $USER` to change to the right user and then edit the file.

**Comment by MainServerSpace** [comment]
> Do you use this container on unRAID or do you use it from the CLI, have you mounted the volumes correctly?
> Just edit the server.cfg file with any editor you want on the host.
> 
> You also have the ability to install vi or nano in the container by typing in `apt update` & `apt install nano` for example, if you do it like that I would also recommend to type in `su $USER` to change to the right user and then edit the file.

This is Unraid sir.

**Comment by ich777** [comment]
Then simply open up your appdata folder through SMB and then edit the file, this should work just fine.

**Comment by MainServerSpace** [comment]
It does work but how do I fix the data persistence issue?

**Comment by MainServerSpace** [comment]
Also default to install is /mnt/cache/appdata/fivem which should be /mnt/user/appdata/fivem

**Comment by ich777** [comment]
I don't understand what you mean with the data persistance issue...
Everything that is stored within the main directory is persistent, that's how containers work, what exactly do you want to have inside the container?

The path is also defined with that in mind, and not by accident, that the FUSE path `/mnt/user/...` can cause troubles some times and that's why it points to the real path that is located at `/mnt/cache/...`
For example TeamFortress2 and many other games have issues when you define the path `/mnt/user/...` or event won't start and segfault over and over again.

May I also ask why you post here and not on the unRAID forums? Most questions where already answered in the support thread wgen you search for FiveM...

**Comment by MainServerSpace** [comment]
I will post on there once I find the thread this is a new to me thing. I usually run it on another pc so new to the docker move. Okay thats understandable I see. What my issue is once I make the changes to config etc. The name is no longer green etc. If I do mkdir -p fivem before docker installing fivem then it stands green but as soon I make changes I lose that.

**Comment by ich777** [comment]
What do you mean with the name is not green, or better speaking where is it not green, you are talking about the docker terminal or the unRAID terminal right?
Why does it need to stay green, also you don't have to create any folders, this is done by the container itself and also everything else so that you have a fully working server, just keep an eye on the logs.

If you want to create a folder/file or copy files to the fivem directory I would recommend to share your `appdata` folder over SMB and then access and copy files that way, hope that makes sense to you... :)

You find the support thread when you click on the icon for the container on the Docker page and then clicking `Support`.
